### ISSUE TITLE
使用rename()无法将版本改名

### ISSUE THREAD

**Issue by akchiji888** [YangSpring114/MinecraftLaunch#2]
rt，我现在有一个名为"1.18.2-forge44.2.0"的mc版本，在第一次使用rename()后，我可以成功的将它改名为"114514"，但当我再次使用rename()后，无法将它的名字"114514"改变为"1919810"，经过检查1.18.2-forge44.2.0.json后，我发现其Id属性还是"114514"而并非"1919810"

**Comment by akchiji888** [comment]
更正：此处的rename应为GameCoreNameChange

**Comment by akchiji888** [comment]
好了，1.9.1里bug修好了

**Comment by akchiji888** [comment]
不是，为啥西路你只改了静态方法却没改实例化后调用的方法？

**Comment by YangSpring114** [comment]
修复了
