### ISSUE TITLE
使用CurseForgeToolkit.GetFeaturesAsync()会返回null

### ISSUE THREAD

**Issue by akchiji888** [YangSpring114/MinecraftLaunch#4]
![image](https://github.com/YangSpring114/MinecraftLaunch/assets/92619820/7376125e-2c99-4bd9-862e-320b3a162e80)
如图，在GetFeaturesAsync()调用ParseCurseForgeModpack()时回报错，导致返回null
ML版本:1.9.1
（已正确初始化CurseForgeToolkit并传入正确的APIKey）

**Comment by YangSpring114** [comment]
此问题现已修复，请移步至新的代码仓库查看
